-- Generado por Oracle SQL Developer Data Modeler 20.4.1.406.0906
--   en:        2021-06-03 23:17:52 CLT
--   sitio:      Oracle Database 11g
--   tipo:      Oracle Database 11g
--------------------------------------------------------
--  DDL for Table RESERVA
--------------------------------------------------------

  CREATE TABLE "ATEMPORADA"."RESERVA" 
   (	"ID_RESERVA" NUMBER(*,0), 
	"DIAS_RESERVA" NUMBER(*,0), 
	"VALOR_FINAL" NUMBER(*,0), 
	"CHECKIN" TIMESTAMP (6), 
	"CHECKOUT" TIMESTAMP (6), 
	"TOTAL_MULTAS" NUMBER(*,0), 
	"FECHA_CONTRATO" TIMESTAMP (6), 
	"METODO_PAGO" VARCHAR2(30 BYTE), 
	"DEPARTAMENTO_ID_DEPARTAMENTO" NUMBER(*,0), 
	"ANTICIPO" NUMBER(*,0), 
	"ESTADODEPAGO" VARCHAR2(20 BYTE), 
	"ESTADO" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CARACTERISTICAS
--------------------------------------------------------

  CREATE TABLE "ATEMPORADA"."CARACTERISTICAS" 
   (	"ID_CARACTERISTICA" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"DESCRIPCION" VARCHAR2(1000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CONDUCTOR
--------------------------------------------------------

  CREATE TABLE "ATEMPORADA"."CONDUCTOR" 
   (	"RUT" VARCHAR2(15 BYTE), 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"APELLIDO" VARCHAR2(50 BYTE), 
	"DISPONIBLE" NUMBER(*,0), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"NRO_CONTACTO" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DEPARTAMENTO
--------------------------------------------------------

  CREATE TABLE "ATEMPORADA"."DEPARTAMENTO" 
   (	"ID_DEPARTAMENTO" NUMBER(*,0), 
	"DIRECCION" VARCHAR2(100 BYTE), 
	"METROS_CUADRADOS" NUMBER, 
	"VALOR_ARRIENDO_DIARIO" NUMBER(*,0), 
	"DISPONBILE" NUMBER(*,0), 
	"ZONA" VARCHAR2(50 BYTE), 
	"NRO_HABITACIONES" NUMBER(*,0), 
	"NRO_BANIOS" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DETALLEMULTA
--------------------------------------------------------

  CREATE TABLE "ATEMPORADA"."DETALLEMULTA" 
   (	"ID_DMULTA" NUMBER(*,0), 
	"OBSERVACIONES" VARCHAR2(1000 BYTE), 
	"RESERVA_ID_RESERVA" NUMBER(*,0), 
	"MULTA_ID_MULTA" NUMBER(*,0), 
	"ESTADOMULTA" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DETALLESERVICIOS
--------------------------------------------------------

  CREATE TABLE "ATEMPORADA"."DETALLESERVICIOS" 
   (	"ID_DETSER" NUMBER(*,0), 
	"PRECIO" NUMBER(*,0), 
	"FECHA" TIMESTAMP (6), 
	"SERVICIOEXTRA_ID_SERVICIO" NUMBER(*,0), 
	"RESERVA_ID_RESERVA" NUMBER(*,0), 
	"TOUR_ID_TOUR" NUMBER(*,0), 
	"VIAJE_ID_VIAJE" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ENCARGADO
--------------------------------------------------------

  CREATE TABLE "ATEMPORADA"."ENCARGADO" 
   (	"RUT" VARCHAR2(15 BYTE), 
	"NRO_CONTACTO" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"APELLIDO" VARCHAR2(50 BYTE), 
	"EMAIL" VARCHAR2(60 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FOTO
--------------------------------------------------------

  CREATE TABLE "ATEMPORADA"."FOTO" 
   (	"ID_FOTO" NUMBER(*,0), 
	"DESCRIPCION" VARCHAR2(1000 BYTE), 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"DEPARTAMENTO_ID_DEPARTAMENTO" NUMBER(*,0), 
	"IMAGEN" BLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("IMAGEN") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table ACOMPANANTE
--------------------------------------------------------

  CREATE TABLE "ATEMPORADA"."ACOMPANANTE" 
   (	"CEDULA" VARCHAR2(15 BYTE), 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"APELLIDO" VARCHAR2(50 BYTE), 
	"TELEFONO" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table INVENTARIO
--------------------------------------------------------

  CREATE TABLE "ATEMPORADA"."INVENTARIO" 
   (	"FECHA_ASIGNACION" TIMESTAMP (6), 
	"FECHA_ULTIMA_MODIFICACION" TIMESTAMP (6), 
	"CANTIDAD" NUMBER(*,0), 
	"ITEMS_ID_ITEM" NUMBER(*,0), 
	"DEPARTAMENTO_ID_DEPARTAMENTO" NUMBER(*,0), 
	"VALOR_TOTAL" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table INVOLUCRADOS
--------------------------------------------------------

  CREATE TABLE "ATEMPORADA"."INVOLUCRADOS" 
   (	"USUARIO_EMAIL" VARCHAR2(60 BYTE), 
	"RESERVA_ID_RESERVA" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ITEMS
--------------------------------------------------------

  CREATE TABLE "ATEMPORADA"."ITEMS" 
   (	"ID_ITEM" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"VALOR" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table LISTACARACTERISTICAS
--------------------------------------------------------

  CREATE TABLE "ATEMPORADA"."LISTACARACTERISTICAS" 
   (	"DEPARTAMENTO_ID_DEPARTAMENTO" NUMBER(*,0), 
	"CARACTERISTICAS_ID_CARACT" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table LISTAACOMPANANTE
--------------------------------------------------------

  CREATE TABLE "ATEMPORADA"."LISTAACOMP" 
   (	"ACOMPANANTE_CEDULA" VARCHAR2(15 BYTE), 
	"RESERVA_ID_RESERVA" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

--------------------------------------------------------
--  DDL for Table MANTENCION
--------------------------------------------------------

  CREATE TABLE "ATEMPORADA"."MANTENCION" 
   (	"ID_MANTENCION" NUMBER(*,0), 
	"VALOR_TOTAL" NUMBER(*,0), 
	"DESCRIPCION" VARCHAR2(1000 BYTE), 
	"FECHA_INICIO" TIMESTAMP (6), 
	"FECHA_TERMINO" TIMESTAMP (6), 
	"MOTIVO" VARCHAR2(50 BYTE), 
	"TIPO_MANTENCION" VARCHAR2(30 BYTE), 
	"ENCARGADO_RUT" VARCHAR2(15 BYTE), 
	"DEPARTAMENTO_ID_DEPARTAMENTO" NUMBER(*,0), 
	"ESTADO" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MULTA
--------------------------------------------------------

  CREATE TABLE "ATEMPORADA"."MULTA" 
   (	"ID_MULTA" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"DESCRIPCION" VARCHAR2(1000 BYTE), 
	"VALOR" NUMBER(*,0), 
	"ESTADO_MULTA" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table REGISTROINVENTARIO
--------------------------------------------------------

  CREATE TABLE "ATEMPORADA"."REGISTROINVENTARIO" 
   (	"FECHA_ASIGNACION" TIMESTAMP (6), 
	"FECHA_ULTIMA_MODIFICACION" TIMESTAMP (6), 
	"ITEMS_ID_ITEM" NUMBER(*,0), 
	"CANTIDAD" NUMBER(*,0), 
	"DEPARTAMENTO_ID_DEPARTAMENTO" NUMBER(*,0), 
	"VALOR_TOTAL" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table REVISION
--------------------------------------------------------

  CREATE TABLE "ATEMPORADA"."REVISION" 
   (	"ESTADO" VARCHAR2(30 BYTE), 
	"OBSERVACIONES" VARCHAR2(500 BYTE), 
	"INVENTARIO_ITEMS_ID_ITEM" NUMBER(*,0), 
	"INVENTARIO_DEPTO_ID_DEPTO" NUMBER(*,0), 
	"RESERVA_ID_RESERVA" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SERVICIOEXTRA
--------------------------------------------------------

  CREATE TABLE "ATEMPORADA"."SERVICIOEXTRA" 
   (	"ID_SERVICIO" NUMBER(*,0), 
	"NOMBRE_SERVICIO" VARCHAR2(50 BYTE), 
	"VALOR_SERVICIO" NUMBER(*,0), 
	"DESCRIPCION" VARCHAR2(1000 BYTE), 
	"DISPONIBLE" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TOUR
--------------------------------------------------------

  CREATE TABLE "ATEMPORADA"."TOUR" 
   (	"ID_TOUR" NUMBER(*,0), 
	"INICIO" TIMESTAMP (6), 
	"TERMINO" TIMESTAMP (6), 
	"ORIGEN" VARCHAR2(50 BYTE), 
	"DESTINO" VARCHAR2(50 BYTE), 
	"RUT_CONDUCTOR" VARCHAR2(15 BYTE), 
	"PATENTE_VEHICULO" VARCHAR2(10 BYTE), 
	"NROPARTICIPANTES" NUMBER(*,0), 
	"VALOR" NUMBER(*,0), 
	"DISPONIBLE" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE  
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USUARIO
--------------------------------------------------------

  CREATE TABLE "ATEMPORADA"."USUARIO" 
   (	"EMAIL" VARCHAR2(60 BYTE), 
	"CEDULA" VARCHAR2(15 BYTE), 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"APELLIDO" VARCHAR2(50 BYTE), 
	"TELEFONO" NUMBER(*,0), 
	"ESTADO" VARCHAR2(15 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE), 
	"TIPO" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table VEHICULO
--------------------------------------------------------

  CREATE TABLE "ATEMPORADA"."VEHICULO" 
   (	"PATENTE" VARCHAR2(10 BYTE), 
	"MODELO" VARCHAR2(30 BYTE), 
	"AÑO" NUMBER(*,0), 
	"COLOR" VARCHAR2(30 BYTE), 
	"DISPONIBLE" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table VIAJE
--------------------------------------------------------

  CREATE TABLE "ATEMPORADA"."VIAJE" 
   (	"ID_VIAJE" NUMBER(*,0), 
	"ORIGEN" VARCHAR2(50 BYTE), 
	"DESTINO" VARCHAR2(50 BYTE), 
	"COMIENZO" TIMESTAMP (6), 
	"PRECIO" NUMBER(*,0), 
	"CONDUCTOR_RUT" VARCHAR2(15 BYTE), 
	"VEHICULO_PATENTE" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

--------------------------------------------------------
--  DDL for Index RESERVA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ATEMPORADA"."RESERVA_PK" ON "ATEMPORADA"."RESERVA" ("ID_RESERVA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CARACTERISTICAS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ATEMPORADA"."CARACTERISTICAS_PK" ON "ATEMPORADA"."CARACTERISTICAS" ("ID_CARACTERISTICA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CONDUCTOR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ATEMPORADA"."CONDUCTOR_PK" ON "ATEMPORADA"."CONDUCTOR" ("RUT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index DEPARTAMENTO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ATEMPORADA"."DEPARTAMENTO_PK" ON "ATEMPORADA"."DEPARTAMENTO" ("ID_DEPARTAMENTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index DETALLEMULTA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ATEMPORADA"."DETALLEMULTA_PK" ON "ATEMPORADA"."DETALLEMULTA" ("ID_DMULTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index DETALLESERVICIOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ATEMPORADA"."DETALLESERVICIOS_PK" ON "ATEMPORADA"."DETALLESERVICIOS" ("RESERVA_ID_RESERVA", "ID_DETSER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ENCARGADO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ATEMPORADA"."ENCARGADO_PK" ON "ATEMPORADA"."ENCARGADO" ("RUT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index FOTO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ATEMPORADA"."FOTO_PK" ON "ATEMPORADA"."FOTO" ("ID_FOTO", "DEPARTAMENTO_ID_DEPARTAMENTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ACOMPANANTE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ATEMPORADA"."ACOMPANANTE_PK" ON "ATEMPORADA"."ACOMPANANTE" ("CEDULA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index INVENTARIO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ATEMPORADA"."INVENTARIO_PK" ON "ATEMPORADA"."INVENTARIO" ("ITEMS_ID_ITEM", "DEPARTAMENTO_ID_DEPARTAMENTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index INVOLUCRADOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ATEMPORADA"."INVOLUCRADOS_PK" ON "ATEMPORADA"."INVOLUCRADOS" ("USUARIO_EMAIL", "RESERVA_ID_RESERVA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ITEMS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ATEMPORADA"."ITEMS_PK" ON "ATEMPORADA"."ITEMS" ("ID_ITEM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index LISTACARACTERISTICAS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ATEMPORADA"."LISTACARACTERISTICAS_PK" ON "ATEMPORADA"."LISTACARACTERISTICAS" ("DEPARTAMENTO_ID_DEPARTAMENTO", "CARACTERISTICAS_ID_CARACT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index LISTAACOMPANANTE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ATEMPORADA"."LISTAACOMP_PK" ON "ATEMPORADA"."LISTAACOMP" ("ACOMPANANTE_CEDULA", "RESERVA_ID_RESERVA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MANTENCION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ATEMPORADA"."MANTENCION_PK" ON "ATEMPORADA"."MANTENCION" ("ID_MANTENCION", "ENCARGADO_RUT", "DEPARTAMENTO_ID_DEPARTAMENTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MULTA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ATEMPORADA"."MULTA_PK" ON "ATEMPORADA"."MULTA" ("ID_MULTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index REVISION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ATEMPORADA"."REVISION_PK" ON "ATEMPORADA"."REVISION" ("INVENTARIO_ITEMS_ID_ITEM", "INVENTARIO_DEPTO_ID_DEPTO", "RESERVA_ID_RESERVA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SERVICIOEXTRA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ATEMPORADA"."SERVICIOEXTRA_PK" ON "ATEMPORADA"."SERVICIOEXTRA" ("ID_SERVICIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TOUR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ATEMPORADA"."TOUR_PK" ON "ATEMPORADA"."TOUR" ("ID_TOUR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index USUARIO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ATEMPORADA"."USUARIO_PK" ON "ATEMPORADA"."USUARIO" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index VEHICULO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ATEMPORADA"."VEHICULO_PK" ON "ATEMPORADA"."VEHICULO" ("PATENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index VIAJE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ATEMPORADA"."VIAJE_PK" ON "ATEMPORADA"."VIAJE" ("ID_VIAJE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table CARACTERISTICAS
--------------------------------------------------------

  ALTER TABLE "ATEMPORADA"."CARACTERISTICAS" MODIFY ("ID_CARACTERISTICA" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."CARACTERISTICAS" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."CARACTERISTICAS" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."CARACTERISTICAS" ADD CONSTRAINT "CARACTERISTICAS_PK" PRIMARY KEY ("ID_CARACTERISTICA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USUARIO
--------------------------------------------------------

  ALTER TABLE "ATEMPORADA"."USUARIO" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."USUARIO" MODIFY ("CEDULA" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."USUARIO" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."USUARIO" MODIFY ("APELLIDO" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."USUARIO" MODIFY ("TELEFONO" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."USUARIO" MODIFY ("ESTADO" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."USUARIO" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."USUARIO" MODIFY ("TIPO" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."USUARIO" ADD CONSTRAINT "USUARIO_PK" PRIMARY KEY ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table RESERVA
--------------------------------------------------------

  ALTER TABLE "ATEMPORADA"."RESERVA" MODIFY ("ID_RESERVA" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."RESERVA" MODIFY ("DIAS_RESERVA" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."RESERVA" MODIFY ("VALOR_FINAL" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."RESERVA" MODIFY ("CHECKIN" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."RESERVA" MODIFY ("CHECKOUT" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."RESERVA" MODIFY ("FECHA_CONTRATO" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."RESERVA" MODIFY ("METODO_PAGO" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."RESERVA" MODIFY ("DEPARTAMENTO_ID_DEPARTAMENTO" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."RESERVA" MODIFY ("ANTICIPO" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."RESERVA" MODIFY ("ESTADODEPAGO" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."RESERVA" MODIFY ("ESTADO" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."RESERVA" ADD CONSTRAINT "RESERVA_PK" PRIMARY KEY ("ID_RESERVA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DEPARTAMENTO
--------------------------------------------------------

  ALTER TABLE "ATEMPORADA"."DEPARTAMENTO" MODIFY ("ID_DEPARTAMENTO" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."DEPARTAMENTO" MODIFY ("DIRECCION" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."DEPARTAMENTO" MODIFY ("METROS_CUADRADOS" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."DEPARTAMENTO" MODIFY ("VALOR_ARRIENDO_DIARIO" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."DEPARTAMENTO" MODIFY ("DISPONBILE" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."DEPARTAMENTO" MODIFY ("ZONA" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."DEPARTAMENTO" MODIFY ("NRO_HABITACIONES" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."DEPARTAMENTO" MODIFY ("NRO_BANIOS" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."DEPARTAMENTO" ADD CONSTRAINT "DEPARTAMENTO_PK" PRIMARY KEY ("ID_DEPARTAMENTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table REGISTROINVENTARIO
--------------------------------------------------------

  ALTER TABLE "ATEMPORADA"."REGISTROINVENTARIO" MODIFY ("FECHA_ASIGNACION" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."REGISTROINVENTARIO" MODIFY ("VALOR_TOTAL" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."REGISTROINVENTARIO" MODIFY ("ITEMS_ID_ITEM" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."REGISTROINVENTARIO" MODIFY ("CANTIDAD" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."REGISTROINVENTARIO" MODIFY ("DEPARTAMENTO_ID_DEPARTAMENTO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ENCARGADO
--------------------------------------------------------

  ALTER TABLE "ATEMPORADA"."ENCARGADO" MODIFY ("RUT" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."ENCARGADO" MODIFY ("NRO_CONTACTO" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."ENCARGADO" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."ENCARGADO" MODIFY ("APELLIDO" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."ENCARGADO" ADD CONSTRAINT "ENCARGADO_PK" PRIMARY KEY ("RUT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table VEHICULO
--------------------------------------------------------

  ALTER TABLE "ATEMPORADA"."VEHICULO" MODIFY ("PATENTE" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."VEHICULO" MODIFY ("MODELO" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."VEHICULO" MODIFY ("AÑO" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."VEHICULO" MODIFY ("COLOR" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."VEHICULO" MODIFY ("DISPONIBLE" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."VEHICULO" ADD CONSTRAINT "VEHICULO_PK" PRIMARY KEY ("PATENTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table INVOLUCRADOS
--------------------------------------------------------

  ALTER TABLE "ATEMPORADA"."INVOLUCRADOS" MODIFY ("USUARIO_EMAIL" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."INVOLUCRADOS" MODIFY ("RESERVA_ID_RESERVA" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."INVOLUCRADOS" ADD CONSTRAINT "INVOLUCRADOS_PK" PRIMARY KEY ("USUARIO_EMAIL", "RESERVA_ID_RESERVA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table REVISION
--------------------------------------------------------

  ALTER TABLE "ATEMPORADA"."REVISION" MODIFY ("ESTADO" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."REVISION" MODIFY ("INVENTARIO_ITEMS_ID_ITEM" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."REVISION" MODIFY ("INVENTARIO_DEPTO_ID_DEPTO" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."REVISION" MODIFY ("RESERVA_ID_RESERVA" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."REVISION" ADD CONSTRAINT "REVISION_PK" PRIMARY KEY ("INVENTARIO_ITEMS_ID_ITEM", "INVENTARIO_DEPTO_ID_DEPTO", "RESERVA_ID_RESERVA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MULTA
--------------------------------------------------------

  ALTER TABLE "ATEMPORADA"."MULTA" MODIFY ("ID_MULTA" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."MULTA" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."MULTA" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."MULTA" MODIFY ("VALOR" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."MULTA" ADD CONSTRAINT "MULTA_PK" PRIMARY KEY ("ID_MULTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ATEMPORADA"."MULTA" MODIFY ("ESTADO_MULTA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CONDUCTOR
--------------------------------------------------------

  ALTER TABLE "ATEMPORADA"."CONDUCTOR" MODIFY ("RUT" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."CONDUCTOR" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."CONDUCTOR" MODIFY ("APELLIDO" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."CONDUCTOR" MODIFY ("DISPONIBLE" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."CONDUCTOR" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."CONDUCTOR" MODIFY ("NRO_CONTACTO" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."CONDUCTOR" ADD CONSTRAINT "CONDUCTOR_PK" PRIMARY KEY ("RUT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DETALLEMULTA
--------------------------------------------------------

  ALTER TABLE "ATEMPORADA"."DETALLEMULTA" MODIFY ("ESTADOMULTA" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."DETALLEMULTA" MODIFY ("ID_DMULTA" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."DETALLEMULTA" MODIFY ("OBSERVACIONES" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."DETALLEMULTA" MODIFY ("RESERVA_ID_RESERVA" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."DETALLEMULTA" MODIFY ("MULTA_ID_MULTA" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."DETALLEMULTA" ADD CONSTRAINT "DETALLEMULTA_PK" PRIMARY KEY ("ID_DMULTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DETALLESERVICIOS
--------------------------------------------------------

  ALTER TABLE "ATEMPORADA"."DETALLESERVICIOS" MODIFY ("SERVICIOEXTRA_ID_SERVICIO" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."DETALLESERVICIOS" MODIFY ("TOUR_ID_TOUR" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."DETALLESERVICIOS" MODIFY ("ID_DETSER" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."DETALLESERVICIOS" MODIFY ("PRECIO" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."DETALLESERVICIOS" MODIFY ("FECHA" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."DETALLESERVICIOS" MODIFY ("RESERVA_ID_RESERVA" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."DETALLESERVICIOS" ADD CONSTRAINT "DETALLESERVICIOS_PK" PRIMARY KEY ("RESERVA_ID_RESERVA", "ID_DETSER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table VIAJE
--------------------------------------------------------

  ALTER TABLE "ATEMPORADA"."VIAJE" MODIFY ("ID_VIAJE" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."VIAJE" MODIFY ("ORIGEN" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."VIAJE" MODIFY ("DESTINO" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."VIAJE" MODIFY ("COMIENZO" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."VIAJE" MODIFY ("PRECIO" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."VIAJE" ADD CONSTRAINT "VIAJE_PK" PRIMARY KEY ("ID_VIAJE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SERVICIOEXTRA
--------------------------------------------------------

  ALTER TABLE "ATEMPORADA"."SERVICIOEXTRA" MODIFY ("ID_SERVICIO" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."SERVICIOEXTRA" MODIFY ("NOMBRE_SERVICIO" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."SERVICIOEXTRA" MODIFY ("VALOR_SERVICIO" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."SERVICIOEXTRA" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."SERVICIOEXTRA" MODIFY ("DISPONIBLE" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."SERVICIOEXTRA" ADD CONSTRAINT "SERVICIOEXTRA_PK" PRIMARY KEY ("ID_SERVICIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table INVENTARIO
--------------------------------------------------------

  ALTER TABLE "ATEMPORADA"."INVENTARIO" MODIFY ("FECHA_ASIGNACION" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."INVENTARIO" MODIFY ("CANTIDAD" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."INVENTARIO" MODIFY ("ITEMS_ID_ITEM" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."INVENTARIO" MODIFY ("DEPARTAMENTO_ID_DEPARTAMENTO" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."INVENTARIO" MODIFY ("VALOR_TOTAL" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."INVENTARIO" ADD CONSTRAINT "INVENTARIO_PK" PRIMARY KEY ("ITEMS_ID_ITEM", "DEPARTAMENTO_ID_DEPARTAMENTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TOUR
--------------------------------------------------------

  ALTER TABLE "ATEMPORADA"."TOUR" MODIFY ("ID_TOUR" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."TOUR" MODIFY ("INICIO" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."TOUR" MODIFY ("TERMINO" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."TOUR" MODIFY ("ORIGEN" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."TOUR" MODIFY ("DESTINO" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."TOUR" MODIFY ("RUT_CONDUCTOR" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."TOUR" MODIFY ("PATENTE_VEHICULO" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."TOUR" MODIFY ("NROPARTICIPANTES" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."TOUR" MODIFY ("VALOR" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."TOUR" MODIFY ("DISPONIBLE" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."TOUR" ADD CONSTRAINT "TOUR_PK" PRIMARY KEY ("ID_TOUR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table LISTAACOMPANANTE
--------------------------------------------------------

  ALTER TABLE "ATEMPORADA"."LISTAACOMP" MODIFY ("ACOMPANANTE_CEDULA" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."LISTAACOMP" MODIFY ("RESERVA_ID_RESERVA" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."LISTAACOMP" ADD CONSTRAINT "LISTAACOMP_PK" PRIMARY KEY ("ACOMPANANTE_CEDULA", "RESERVA_ID_RESERVA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FOTO
--------------------------------------------------------

  ALTER TABLE "ATEMPORADA"."FOTO" MODIFY ("ID_FOTO" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."FOTO" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."FOTO" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."FOTO" MODIFY ("IMAGEN" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."FOTO" MODIFY ("DEPARTAMENTO_ID_DEPARTAMENTO" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."FOTO" ADD CONSTRAINT "FOTO_PK" PRIMARY KEY ("ID_FOTO", "DEPARTAMENTO_ID_DEPARTAMENTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;

--------------------------------------------------------
--  Constraints for Table ACOMPANANTE
--------------------------------------------------------

  ALTER TABLE "ATEMPORADA"."ACOMPANANTE" MODIFY ("CEDULA" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."ACOMPANANTE" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."ACOMPANANTE" MODIFY ("APELLIDO" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."ACOMPANANTE" MODIFY ("TELEFONO" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."ACOMPANANTE" ADD CONSTRAINT "ACOMPANANTE_PK" PRIMARY KEY ("CEDULA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table LISTACARACTERISTICAS
--------------------------------------------------------

  ALTER TABLE "ATEMPORADA"."LISTACARACTERISTICAS" MODIFY ("DEPARTAMENTO_ID_DEPARTAMENTO" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."LISTACARACTERISTICAS" MODIFY ("CARACTERISTICAS_ID_CARACT" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."LISTACARACTERISTICAS" ADD CONSTRAINT "LISTACARACTERISTICAS_PK" PRIMARY KEY ("DEPARTAMENTO_ID_DEPARTAMENTO", "CARACTERISTICAS_ID_CARACT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MANTENCION
--------------------------------------------------------

  ALTER TABLE "ATEMPORADA"."MANTENCION" MODIFY ("ID_MANTENCION" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."MANTENCION" MODIFY ("VALOR_TOTAL" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."MANTENCION" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."MANTENCION" MODIFY ("FECHA_INICIO" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."MANTENCION" MODIFY ("FECHA_TERMINO" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."MANTENCION" MODIFY ("MOTIVO" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."MANTENCION" MODIFY ("TIPO_MANTENCION" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."MANTENCION" MODIFY ("ENCARGADO_RUT" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."MANTENCION" MODIFY ("DEPARTAMENTO_ID_DEPARTAMENTO" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."MANTENCION" MODIFY ("ESTADO" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."MANTENCION" ADD CONSTRAINT "MANTENCION_PK" PRIMARY KEY ("ID_MANTENCION", "ENCARGADO_RUT", "DEPARTAMENTO_ID_DEPARTAMENTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ITEMS
--------------------------------------------------------

  ALTER TABLE "ATEMPORADA"."ITEMS" MODIFY ("ID_ITEM" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."ITEMS" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."ITEMS" MODIFY ("VALOR" NOT NULL ENABLE);
  ALTER TABLE "ATEMPORADA"."ITEMS" ADD CONSTRAINT "ITEMS_PK" PRIMARY KEY ("ID_ITEM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RESERVA
--------------------------------------------------------

  ALTER TABLE "ATEMPORADA"."RESERVA" ADD CONSTRAINT "RESERVA_DEPARTAMENTO_FK" FOREIGN KEY ("DEPARTAMENTO_ID_DEPARTAMENTO")
	  REFERENCES "ATEMPORADA"."DEPARTAMENTO" ("ID_DEPARTAMENTO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DETALLEMULTA
--------------------------------------------------------

  ALTER TABLE "ATEMPORADA"."DETALLEMULTA" ADD CONSTRAINT "DETALLEMULTA_RESERVA_FK" FOREIGN KEY ("RESERVA_ID_RESERVA")
	  REFERENCES "ATEMPORADA"."RESERVA" ("ID_RESERVA") ENABLE;
  ALTER TABLE "ATEMPORADA"."DETALLEMULTA" ADD CONSTRAINT "DETALLEMULTA_MULTA_FK" FOREIGN KEY ("MULTA_ID_MULTA")
	  REFERENCES "ATEMPORADA"."MULTA" ("ID_MULTA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DETALLESERVICIOS
--------------------------------------------------------

  ALTER TABLE "ATEMPORADA"."DETALLESERVICIOS" ADD CONSTRAINT "DETALLESERVICIOS_RESERVA_FK" FOREIGN KEY ("RESERVA_ID_RESERVA")
	  REFERENCES "ATEMPORADA"."RESERVA" ("ID_RESERVA") ENABLE;
  ALTER TABLE "ATEMPORADA"."DETALLESERVICIOS" ADD CONSTRAINT "DETALLESERVICIOS_SERVICIOEX_FK" FOREIGN KEY ("SERVICIOEXTRA_ID_SERVICIO")
	  REFERENCES "ATEMPORADA"."SERVICIOEXTRA" ("ID_SERVICIO") ENABLE;
  ALTER TABLE "ATEMPORADA"."DETALLESERVICIOS" ADD CONSTRAINT "DETALLESERVICIOS_TOUR_FK" FOREIGN KEY ("TOUR_ID_TOUR")
	  REFERENCES "ATEMPORADA"."TOUR" ("ID_TOUR") ENABLE;
  ALTER TABLE "ATEMPORADA"."DETALLESERVICIOS" ADD CONSTRAINT "DETALLESERVICIOS_VIAJE_FK" FOREIGN KEY ("VIAJE_ID_VIAJE")
	  REFERENCES "ATEMPORADA"."VIAJE" ("ID_VIAJE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FOTO
--------------------------------------------------------

  ALTER TABLE "ATEMPORADA"."FOTO" ADD CONSTRAINT "FOTO_DEPARTAMENTO_FK" FOREIGN KEY ("DEPARTAMENTO_ID_DEPARTAMENTO")
	  REFERENCES "ATEMPORADA"."DEPARTAMENTO" ("ID_DEPARTAMENTO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table INVENTARIO
--------------------------------------------------------

  ALTER TABLE "ATEMPORADA"."INVENTARIO" ADD CONSTRAINT "INVENTARIO_DEPARTAMENTO_FK" FOREIGN KEY ("DEPARTAMENTO_ID_DEPARTAMENTO")
	  REFERENCES "ATEMPORADA"."DEPARTAMENTO" ("ID_DEPARTAMENTO") ENABLE;
  ALTER TABLE "ATEMPORADA"."INVENTARIO" ADD CONSTRAINT "INVENTARIO_ITEMS_FK" FOREIGN KEY ("ITEMS_ID_ITEM")
	  REFERENCES "ATEMPORADA"."ITEMS" ("ID_ITEM") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table INVOLUCRADOS
--------------------------------------------------------

  ALTER TABLE "ATEMPORADA"."INVOLUCRADOS" ADD CONSTRAINT "INVOLUCRADOS_RESERVA_FK" FOREIGN KEY ("RESERVA_ID_RESERVA")
	  REFERENCES "ATEMPORADA"."RESERVA" ("ID_RESERVA") ENABLE;
  ALTER TABLE "ATEMPORADA"."INVOLUCRADOS" ADD CONSTRAINT "INVOLUCRADOS_USUARIO_FK" FOREIGN KEY ("USUARIO_EMAIL")
	  REFERENCES "ATEMPORADA"."USUARIO" ("EMAIL") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table LISTACARACTERISTICAS
--------------------------------------------------------

  ALTER TABLE "ATEMPORADA"."LISTACARACTERISTICAS" ADD CONSTRAINT "LISTACARACTERISTICAS_CARACT_FK" FOREIGN KEY ("CARACTERISTICAS_ID_CARACT")
	  REFERENCES "ATEMPORADA"."CARACTERISTICAS" ("ID_CARACTERISTICA") ENABLE;
  ALTER TABLE "ATEMPORADA"."LISTACARACTERISTICAS" ADD CONSTRAINT "LISTACARACTERISTICAS_DEPTO_FK" FOREIGN KEY ("DEPARTAMENTO_ID_DEPARTAMENTO")
	  REFERENCES "ATEMPORADA"."DEPARTAMENTO" ("ID_DEPARTAMENTO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table LISTAACOMPANANTE
--------------------------------------------------------

  ALTER TABLE "ATEMPORADA"."LISTAACOMP" ADD CONSTRAINT "LISTAACOMP_RESERVA_FK" FOREIGN KEY ("RESERVA_ID_RESERVA")
	  REFERENCES "ATEMPORADA"."RESERVA" ("ID_RESERVA") ENABLE;
  ALTER TABLE "ATEMPORADA"."LISTAACOMP" ADD CONSTRAINT "LISTAACOMP_ACOMPANANTE_FK" FOREIGN KEY ("ACOMPANANTE_CEDULA")
	  REFERENCES "ATEMPORADA"."ACOMPANANTE" ("CEDULA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MANTENCION
--------------------------------------------------------

  ALTER TABLE "ATEMPORADA"."MANTENCION" ADD CONSTRAINT "MANTENCION_DEPARTAMENTO_FK" FOREIGN KEY ("DEPARTAMENTO_ID_DEPARTAMENTO")
	  REFERENCES "ATEMPORADA"."DEPARTAMENTO" ("ID_DEPARTAMENTO") ENABLE;
  ALTER TABLE "ATEMPORADA"."MANTENCION" ADD CONSTRAINT "MANTENCION_ENCARGADO_FK" FOREIGN KEY ("ENCARGADO_RUT")
	  REFERENCES "ATEMPORADA"."ENCARGADO" ("RUT") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REGISTROINVENTARIO
--------------------------------------------------------

  ALTER TABLE "ATEMPORADA"."REGISTROINVENTARIO" ADD CONSTRAINT "REGISTROINVENTARIO_DEPTO_FK" FOREIGN KEY ("DEPARTAMENTO_ID_DEPARTAMENTO")
	  REFERENCES "ATEMPORADA"."DEPARTAMENTO" ("ID_DEPARTAMENTO") ENABLE;
  ALTER TABLE "ATEMPORADA"."REGISTROINVENTARIO" ADD CONSTRAINT "REGISTROINVENTARIO_ITEMS_FK" FOREIGN KEY ("ITEMS_ID_ITEM")
	  REFERENCES "ATEMPORADA"."ITEMS" ("ID_ITEM") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REVISION
--------------------------------------------------------

  ALTER TABLE "ATEMPORADA"."REVISION" ADD CONSTRAINT "REVISION_RESERVA_FK" FOREIGN KEY ("RESERVA_ID_RESERVA")
	  REFERENCES "ATEMPORADA"."RESERVA" ("ID_RESERVA") ENABLE;
  ALTER TABLE "ATEMPORADA"."REVISION" ADD CONSTRAINT "REVISION_INVENTARIO_FK" FOREIGN KEY ("INVENTARIO_ITEMS_ID_ITEM", "INVENTARIO_DEPTO_ID_DEPTO")
	  REFERENCES "ATEMPORADA"."INVENTARIO" ("ITEMS_ID_ITEM", "DEPARTAMENTO_ID_DEPARTAMENTO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table VIAJE
--------------------------------------------------------

  ALTER TABLE "ATEMPORADA"."VIAJE" ADD CONSTRAINT "VIAJE_CONDUCTOR_FK" FOREIGN KEY ("CONDUCTOR_RUT")
	  REFERENCES "ATEMPORADA"."CONDUCTOR" ("RUT") ENABLE;
  ALTER TABLE "ATEMPORADA"."VIAJE" ADD CONSTRAINT "VIAJE_VEHICULO_FK" FOREIGN KEY ("VEHICULO_PATENTE")
	  REFERENCES "ATEMPORADA"."VEHICULO" ("PATENTE") ENABLE;