//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArriendoTemporada.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACOMPANANTE
    {
        public ACOMPANANTE()
        {
            this.RESERVA = new HashSet<RESERVA>();
        }
    
        public int ID_ACOMPANANTE { get; set; }
        public string RUT_ACOMPANANTE { get; set; }
        public string PASAPORTE { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDO_P { get; set; }
        public string APELLIDO_M { get; set; }
    
        public virtual ICollection<RESERVA> RESERVA { get; set; }
    }
}
