//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArriendoTemporada.DALC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class ArriendoTemporadaEntities : DbContext
    {
        public ArriendoTemporadaEntities()
            : base("name=ArriendoTemporadaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ACOMPANANTE> ACOMPANANTE { get; set; }
        public DbSet<CHECKEO> CHECKEO { get; set; }
        public DbSet<CLIENTE> CLIENTE { get; set; }
        public DbSet<DPTO> DPTO { get; set; }
        public DbSet<INVENTARIO> INVENTARIO { get; set; }
        public DbSet<MANTENCION> MANTENCION { get; set; }
        public DbSet<MULTA> MULTA { get; set; }
        public DbSet<PAGO> PAGO { get; set; }
        public DbSet<RESERVA> RESERVA { get; set; }
        public DbSet<REVISION_INV> REVISION_INV { get; set; }
        public DbSet<SERVICIO> SERVICIO { get; set; }
        public DbSet<TRANSBANK> TRANSBANK { get; set; }
        public DbSet<USUARIO> USUARIO { get; set; }
        public DbSet<GASTOS> GASTOS { get; set; }
        public DbSet<RESERVA_SERVICIO> RESERVA_SERVICIO { get; set; }
    
        public virtual int DELETE_INVENTARIO(Nullable<decimal> iD_INVD)
        {
            var iD_INVDParameter = iD_INVD.HasValue ?
                new ObjectParameter("ID_INVD", iD_INVD) :
                new ObjectParameter("ID_INVD", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DELETE_INVENTARIO", iD_INVDParameter);
        }
    
        public virtual int DELETE_RESERVA(Nullable<decimal> iD_RESERVAD)
        {
            var iD_RESERVADParameter = iD_RESERVAD.HasValue ?
                new ObjectParameter("ID_RESERVAD", iD_RESERVAD) :
                new ObjectParameter("ID_RESERVAD", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DELETE_RESERVA", iD_RESERVADParameter);
        }
    
        public virtual int DELETE_SERVICIO(Nullable<decimal> iD_SERVICIOD)
        {
            var iD_SERVICIODParameter = iD_SERVICIOD.HasValue ?
                new ObjectParameter("ID_SERVICIOD", iD_SERVICIOD) :
                new ObjectParameter("ID_SERVICIOD", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DELETE_SERVICIO", iD_SERVICIODParameter);
        }
    
        public virtual int INHABILITAR_CLIENTE(Nullable<decimal> iD_CLIENTE)
        {
            var iD_CLIENTEParameter = iD_CLIENTE.HasValue ?
                new ObjectParameter("ID_CLIENTE", iD_CLIENTE) :
                new ObjectParameter("ID_CLIENTE", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INHABILITAR_CLIENTE", iD_CLIENTEParameter);
        }
    
        public virtual int INHABILITAR_DPTO(Nullable<decimal> iD_DPTO)
        {
            var iD_DPTOParameter = iD_DPTO.HasValue ?
                new ObjectParameter("ID_DPTO", iD_DPTO) :
                new ObjectParameter("ID_DPTO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INHABILITAR_DPTO", iD_DPTOParameter);
        }
    
        public virtual int INHABILITAR_USUARIO(string rUT_USUARIO)
        {
            var rUT_USUARIOParameter = rUT_USUARIO != null ?
                new ObjectParameter("RUT_USUARIO", rUT_USUARIO) :
                new ObjectParameter("RUT_USUARIO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INHABILITAR_USUARIO", rUT_USUARIOParameter);
        }
    
        public virtual int INSERT_CLIENTE(string rUT_CLIENTE, string pASAPORTE, string pASSWRD, string nOMBRE, string aPELLIDO_P, string aPELLIDO_M, Nullable<decimal> nUM_CELULAR, string cORREO, string nACIONALIDAD, string cLIENTE_FRECUENTE, string eSTADO_CLIENTE)
        {
            var rUT_CLIENTEParameter = rUT_CLIENTE != null ?
                new ObjectParameter("RUT_CLIENTE", rUT_CLIENTE) :
                new ObjectParameter("RUT_CLIENTE", typeof(string));
    
            var pASAPORTEParameter = pASAPORTE != null ?
                new ObjectParameter("PASAPORTE", pASAPORTE) :
                new ObjectParameter("PASAPORTE", typeof(string));
    
            var pASSWRDParameter = pASSWRD != null ?
                new ObjectParameter("PASSWRD", pASSWRD) :
                new ObjectParameter("PASSWRD", typeof(string));
    
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            var aPELLIDO_PParameter = aPELLIDO_P != null ?
                new ObjectParameter("APELLIDO_P", aPELLIDO_P) :
                new ObjectParameter("APELLIDO_P", typeof(string));
    
            var aPELLIDO_MParameter = aPELLIDO_M != null ?
                new ObjectParameter("APELLIDO_M", aPELLIDO_M) :
                new ObjectParameter("APELLIDO_M", typeof(string));
    
            var nUM_CELULARParameter = nUM_CELULAR.HasValue ?
                new ObjectParameter("NUM_CELULAR", nUM_CELULAR) :
                new ObjectParameter("NUM_CELULAR", typeof(decimal));
    
            var cORREOParameter = cORREO != null ?
                new ObjectParameter("CORREO", cORREO) :
                new ObjectParameter("CORREO", typeof(string));
    
            var nACIONALIDADParameter = nACIONALIDAD != null ?
                new ObjectParameter("NACIONALIDAD", nACIONALIDAD) :
                new ObjectParameter("NACIONALIDAD", typeof(string));
    
            var cLIENTE_FRECUENTEParameter = cLIENTE_FRECUENTE != null ?
                new ObjectParameter("CLIENTE_FRECUENTE", cLIENTE_FRECUENTE) :
                new ObjectParameter("CLIENTE_FRECUENTE", typeof(string));
    
            var eSTADO_CLIENTEParameter = eSTADO_CLIENTE != null ?
                new ObjectParameter("ESTADO_CLIENTE", eSTADO_CLIENTE) :
                new ObjectParameter("ESTADO_CLIENTE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERT_CLIENTE", rUT_CLIENTEParameter, pASAPORTEParameter, pASSWRDParameter, nOMBREParameter, aPELLIDO_PParameter, aPELLIDO_MParameter, nUM_CELULARParameter, cORREOParameter, nACIONALIDADParameter, cLIENTE_FRECUENTEParameter, eSTADO_CLIENTEParameter);
        }
    
        public virtual int INSERT_DPTO(string nUM_DEPTO, string dIRECCION, string dESCRIPCION, string rEGION, string eSTADO, Nullable<decimal> vALOR_DIARIO)
        {
            var nUM_DEPTOParameter = nUM_DEPTO != null ?
                new ObjectParameter("NUM_DEPTO", nUM_DEPTO) :
                new ObjectParameter("NUM_DEPTO", typeof(string));
    
            var dIRECCIONParameter = dIRECCION != null ?
                new ObjectParameter("DIRECCION", dIRECCION) :
                new ObjectParameter("DIRECCION", typeof(string));
    
            var dESCRIPCIONParameter = dESCRIPCION != null ?
                new ObjectParameter("DESCRIPCION", dESCRIPCION) :
                new ObjectParameter("DESCRIPCION", typeof(string));
    
            var rEGIONParameter = rEGION != null ?
                new ObjectParameter("REGION", rEGION) :
                new ObjectParameter("REGION", typeof(string));
    
            var eSTADOParameter = eSTADO != null ?
                new ObjectParameter("ESTADO", eSTADO) :
                new ObjectParameter("ESTADO", typeof(string));
    
            var vALOR_DIARIOParameter = vALOR_DIARIO.HasValue ?
                new ObjectParameter("VALOR_DIARIO", vALOR_DIARIO) :
                new ObjectParameter("VALOR_DIARIO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERT_DPTO", nUM_DEPTOParameter, dIRECCIONParameter, dESCRIPCIONParameter, rEGIONParameter, eSTADOParameter, vALOR_DIARIOParameter);
        }
    
        public virtual int INSERT_INVENTARIO(string nOMBRE_ARTI, string tIPO_ARTI, Nullable<decimal> vALOR_ARTI, Nullable<decimal> dPTO_ID_DPTO)
        {
            var nOMBRE_ARTIParameter = nOMBRE_ARTI != null ?
                new ObjectParameter("NOMBRE_ARTI", nOMBRE_ARTI) :
                new ObjectParameter("NOMBRE_ARTI", typeof(string));
    
            var tIPO_ARTIParameter = tIPO_ARTI != null ?
                new ObjectParameter("TIPO_ARTI", tIPO_ARTI) :
                new ObjectParameter("TIPO_ARTI", typeof(string));
    
            var vALOR_ARTIParameter = vALOR_ARTI.HasValue ?
                new ObjectParameter("VALOR_ARTI", vALOR_ARTI) :
                new ObjectParameter("VALOR_ARTI", typeof(decimal));
    
            var dPTO_ID_DPTOParameter = dPTO_ID_DPTO.HasValue ?
                new ObjectParameter("DPTO_ID_DPTO", dPTO_ID_DPTO) :
                new ObjectParameter("DPTO_ID_DPTO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERT_INVENTARIO", nOMBRE_ARTIParameter, tIPO_ARTIParameter, vALOR_ARTIParameter, dPTO_ID_DPTOParameter);
        }
    
        public virtual int INSERT_RESERVA(Nullable<System.DateTime> fECHA_INICIO, Nullable<System.DateTime> fECHA_FIN, Nullable<decimal> eSTADO, Nullable<decimal> cLIENTE_ID_CLIENTE)
        {
            var fECHA_INICIOParameter = fECHA_INICIO.HasValue ?
                new ObjectParameter("FECHA_INICIO", fECHA_INICIO) :
                new ObjectParameter("FECHA_INICIO", typeof(System.DateTime));
    
            var fECHA_FINParameter = fECHA_FIN.HasValue ?
                new ObjectParameter("FECHA_FIN", fECHA_FIN) :
                new ObjectParameter("FECHA_FIN", typeof(System.DateTime));
    
            var eSTADOParameter = eSTADO.HasValue ?
                new ObjectParameter("ESTADO", eSTADO) :
                new ObjectParameter("ESTADO", typeof(decimal));
    
            var cLIENTE_ID_CLIENTEParameter = cLIENTE_ID_CLIENTE.HasValue ?
                new ObjectParameter("CLIENTE_ID_CLIENTE", cLIENTE_ID_CLIENTE) :
                new ObjectParameter("CLIENTE_ID_CLIENTE", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERT_RESERVA", fECHA_INICIOParameter, fECHA_FINParameter, eSTADOParameter, cLIENTE_ID_CLIENTEParameter);
        }
    
        public virtual int INSERT_SERVICIO(string nOMBRE, string tIPO, Nullable<System.DateTime> hORARIO_INICIO, Nullable<System.DateTime> hORARIO_FIN, string pUNTO_REUNION, Nullable<decimal> vALOR, string rECORRIDO, string vEHICULO, string cHOFER)
        {
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            var tIPOParameter = tIPO != null ?
                new ObjectParameter("TIPO", tIPO) :
                new ObjectParameter("TIPO", typeof(string));
    
            var hORARIO_INICIOParameter = hORARIO_INICIO.HasValue ?
                new ObjectParameter("HORARIO_INICIO", hORARIO_INICIO) :
                new ObjectParameter("HORARIO_INICIO", typeof(System.DateTime));
    
            var hORARIO_FINParameter = hORARIO_FIN.HasValue ?
                new ObjectParameter("HORARIO_FIN", hORARIO_FIN) :
                new ObjectParameter("HORARIO_FIN", typeof(System.DateTime));
    
            var pUNTO_REUNIONParameter = pUNTO_REUNION != null ?
                new ObjectParameter("PUNTO_REUNION", pUNTO_REUNION) :
                new ObjectParameter("PUNTO_REUNION", typeof(string));
    
            var vALORParameter = vALOR.HasValue ?
                new ObjectParameter("VALOR", vALOR) :
                new ObjectParameter("VALOR", typeof(decimal));
    
            var rECORRIDOParameter = rECORRIDO != null ?
                new ObjectParameter("RECORRIDO", rECORRIDO) :
                new ObjectParameter("RECORRIDO", typeof(string));
    
            var vEHICULOParameter = vEHICULO != null ?
                new ObjectParameter("VEHICULO", vEHICULO) :
                new ObjectParameter("VEHICULO", typeof(string));
    
            var cHOFERParameter = cHOFER != null ?
                new ObjectParameter("CHOFER", cHOFER) :
                new ObjectParameter("CHOFER", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERT_SERVICIO", nOMBREParameter, tIPOParameter, hORARIO_INICIOParameter, hORARIO_FINParameter, pUNTO_REUNIONParameter, vALORParameter, rECORRIDOParameter, vEHICULOParameter, cHOFERParameter);
        }
    
        public virtual int INSERT_USUARIO(string rUT_USUARIO, string cONTRASENIA, string rOL, string nOMBRE_USUARIO, string aPELLIDO_P, string aPELLIDO_M, string eSTADO_USUARIO, string eMAIL)
        {
            var rUT_USUARIOParameter = rUT_USUARIO != null ?
                new ObjectParameter("RUT_USUARIO", rUT_USUARIO) :
                new ObjectParameter("RUT_USUARIO", typeof(string));
    
            var cONTRASENIAParameter = cONTRASENIA != null ?
                new ObjectParameter("CONTRASENIA", cONTRASENIA) :
                new ObjectParameter("CONTRASENIA", typeof(string));
    
            var rOLParameter = rOL != null ?
                new ObjectParameter("ROL", rOL) :
                new ObjectParameter("ROL", typeof(string));
    
            var nOMBRE_USUARIOParameter = nOMBRE_USUARIO != null ?
                new ObjectParameter("NOMBRE_USUARIO", nOMBRE_USUARIO) :
                new ObjectParameter("NOMBRE_USUARIO", typeof(string));
    
            var aPELLIDO_PParameter = aPELLIDO_P != null ?
                new ObjectParameter("APELLIDO_P", aPELLIDO_P) :
                new ObjectParameter("APELLIDO_P", typeof(string));
    
            var aPELLIDO_MParameter = aPELLIDO_M != null ?
                new ObjectParameter("APELLIDO_M", aPELLIDO_M) :
                new ObjectParameter("APELLIDO_M", typeof(string));
    
            var eSTADO_USUARIOParameter = eSTADO_USUARIO != null ?
                new ObjectParameter("ESTADO_USUARIO", eSTADO_USUARIO) :
                new ObjectParameter("ESTADO_USUARIO", typeof(string));
    
            var eMAILParameter = eMAIL != null ?
                new ObjectParameter("EMAIL", eMAIL) :
                new ObjectParameter("EMAIL", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERT_USUARIO", rUT_USUARIOParameter, cONTRASENIAParameter, rOLParameter, nOMBRE_USUARIOParameter, aPELLIDO_PParameter, aPELLIDO_MParameter, eSTADO_USUARIOParameter, eMAILParameter);
        }
    
        public virtual int UPDATE_CLIENTE(Nullable<decimal> iD_CLIENTEU, string rUT_CLIENTEU, string pASAPORTEU, string pASSWRDU, string nOMBREU, string aPELLIDO_PU, string aPELLIDO_MU, string nUM_CELULARU, string cORREOU, string nACIONALIDADU, string cLIENTE_FRECUENTEU, string eSTADO_CLIENTEU)
        {
            var iD_CLIENTEUParameter = iD_CLIENTEU.HasValue ?
                new ObjectParameter("ID_CLIENTEU", iD_CLIENTEU) :
                new ObjectParameter("ID_CLIENTEU", typeof(decimal));
    
            var rUT_CLIENTEUParameter = rUT_CLIENTEU != null ?
                new ObjectParameter("RUT_CLIENTEU", rUT_CLIENTEU) :
                new ObjectParameter("RUT_CLIENTEU", typeof(string));
    
            var pASAPORTEUParameter = pASAPORTEU != null ?
                new ObjectParameter("PASAPORTEU", pASAPORTEU) :
                new ObjectParameter("PASAPORTEU", typeof(string));
    
            var pASSWRDUParameter = pASSWRDU != null ?
                new ObjectParameter("PASSWRDU", pASSWRDU) :
                new ObjectParameter("PASSWRDU", typeof(string));
    
            var nOMBREUParameter = nOMBREU != null ?
                new ObjectParameter("NOMBREU", nOMBREU) :
                new ObjectParameter("NOMBREU", typeof(string));
    
            var aPELLIDO_PUParameter = aPELLIDO_PU != null ?
                new ObjectParameter("APELLIDO_PU", aPELLIDO_PU) :
                new ObjectParameter("APELLIDO_PU", typeof(string));
    
            var aPELLIDO_MUParameter = aPELLIDO_MU != null ?
                new ObjectParameter("APELLIDO_MU", aPELLIDO_MU) :
                new ObjectParameter("APELLIDO_MU", typeof(string));
    
            var nUM_CELULARUParameter = nUM_CELULARU != null ?
                new ObjectParameter("NUM_CELULARU", nUM_CELULARU) :
                new ObjectParameter("NUM_CELULARU", typeof(string));
    
            var cORREOUParameter = cORREOU != null ?
                new ObjectParameter("CORREOU", cORREOU) :
                new ObjectParameter("CORREOU", typeof(string));
    
            var nACIONALIDADUParameter = nACIONALIDADU != null ?
                new ObjectParameter("NACIONALIDADU", nACIONALIDADU) :
                new ObjectParameter("NACIONALIDADU", typeof(string));
    
            var cLIENTE_FRECUENTEUParameter = cLIENTE_FRECUENTEU != null ?
                new ObjectParameter("CLIENTE_FRECUENTEU", cLIENTE_FRECUENTEU) :
                new ObjectParameter("CLIENTE_FRECUENTEU", typeof(string));
    
            var eSTADO_CLIENTEUParameter = eSTADO_CLIENTEU != null ?
                new ObjectParameter("ESTADO_CLIENTEU", eSTADO_CLIENTEU) :
                new ObjectParameter("ESTADO_CLIENTEU", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDATE_CLIENTE", iD_CLIENTEUParameter, rUT_CLIENTEUParameter, pASAPORTEUParameter, pASSWRDUParameter, nOMBREUParameter, aPELLIDO_PUParameter, aPELLIDO_MUParameter, nUM_CELULARUParameter, cORREOUParameter, nACIONALIDADUParameter, cLIENTE_FRECUENTEUParameter, eSTADO_CLIENTEUParameter);
        }
    
        public virtual int UPDATE_DPTO(Nullable<decimal> iD_DPTOU, string nUM_DEPTOU, string dIRECCIONU, string dESCRIPCIONU, string rEGIONU, string eSTADOU, Nullable<decimal> vALOR_DIARIOU)
        {
            var iD_DPTOUParameter = iD_DPTOU.HasValue ?
                new ObjectParameter("ID_DPTOU", iD_DPTOU) :
                new ObjectParameter("ID_DPTOU", typeof(decimal));
    
            var nUM_DEPTOUParameter = nUM_DEPTOU != null ?
                new ObjectParameter("NUM_DEPTOU", nUM_DEPTOU) :
                new ObjectParameter("NUM_DEPTOU", typeof(string));
    
            var dIRECCIONUParameter = dIRECCIONU != null ?
                new ObjectParameter("DIRECCIONU", dIRECCIONU) :
                new ObjectParameter("DIRECCIONU", typeof(string));
    
            var dESCRIPCIONUParameter = dESCRIPCIONU != null ?
                new ObjectParameter("DESCRIPCIONU", dESCRIPCIONU) :
                new ObjectParameter("DESCRIPCIONU", typeof(string));
    
            var rEGIONUParameter = rEGIONU != null ?
                new ObjectParameter("REGIONU", rEGIONU) :
                new ObjectParameter("REGIONU", typeof(string));
    
            var eSTADOUParameter = eSTADOU != null ?
                new ObjectParameter("ESTADOU", eSTADOU) :
                new ObjectParameter("ESTADOU", typeof(string));
    
            var vALOR_DIARIOUParameter = vALOR_DIARIOU.HasValue ?
                new ObjectParameter("VALOR_DIARIOU", vALOR_DIARIOU) :
                new ObjectParameter("VALOR_DIARIOU", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDATE_DPTO", iD_DPTOUParameter, nUM_DEPTOUParameter, dIRECCIONUParameter, dESCRIPCIONUParameter, rEGIONUParameter, eSTADOUParameter, vALOR_DIARIOUParameter);
        }
    
        public virtual int UPDATE_INVENTARIO(Nullable<decimal> iD_INVU, string nOMBRE_ARTIU, string tIPO_ARTIU, Nullable<decimal> vALOR_ARTIU, Nullable<decimal> dPTO_ID_DPTOU)
        {
            var iD_INVUParameter = iD_INVU.HasValue ?
                new ObjectParameter("ID_INVU", iD_INVU) :
                new ObjectParameter("ID_INVU", typeof(decimal));
    
            var nOMBRE_ARTIUParameter = nOMBRE_ARTIU != null ?
                new ObjectParameter("NOMBRE_ARTIU", nOMBRE_ARTIU) :
                new ObjectParameter("NOMBRE_ARTIU", typeof(string));
    
            var tIPO_ARTIUParameter = tIPO_ARTIU != null ?
                new ObjectParameter("TIPO_ARTIU", tIPO_ARTIU) :
                new ObjectParameter("TIPO_ARTIU", typeof(string));
    
            var vALOR_ARTIUParameter = vALOR_ARTIU.HasValue ?
                new ObjectParameter("VALOR_ARTIU", vALOR_ARTIU) :
                new ObjectParameter("VALOR_ARTIU", typeof(decimal));
    
            var dPTO_ID_DPTOUParameter = dPTO_ID_DPTOU.HasValue ?
                new ObjectParameter("DPTO_ID_DPTOU", dPTO_ID_DPTOU) :
                new ObjectParameter("DPTO_ID_DPTOU", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDATE_INVENTARIO", iD_INVUParameter, nOMBRE_ARTIUParameter, tIPO_ARTIUParameter, vALOR_ARTIUParameter, dPTO_ID_DPTOUParameter);
        }
    
        public virtual int UPDATE_RESERVA(Nullable<decimal> iD_RESERVAU, Nullable<System.DateTime> fECHA_INICIOU, Nullable<System.DateTime> fECHA_FINU, Nullable<decimal> eSTADOU, Nullable<decimal> cLIENTE_ID_CLIENTEU)
        {
            var iD_RESERVAUParameter = iD_RESERVAU.HasValue ?
                new ObjectParameter("ID_RESERVAU", iD_RESERVAU) :
                new ObjectParameter("ID_RESERVAU", typeof(decimal));
    
            var fECHA_INICIOUParameter = fECHA_INICIOU.HasValue ?
                new ObjectParameter("FECHA_INICIOU", fECHA_INICIOU) :
                new ObjectParameter("FECHA_INICIOU", typeof(System.DateTime));
    
            var fECHA_FINUParameter = fECHA_FINU.HasValue ?
                new ObjectParameter("FECHA_FINU", fECHA_FINU) :
                new ObjectParameter("FECHA_FINU", typeof(System.DateTime));
    
            var eSTADOUParameter = eSTADOU.HasValue ?
                new ObjectParameter("ESTADOU", eSTADOU) :
                new ObjectParameter("ESTADOU", typeof(decimal));
    
            var cLIENTE_ID_CLIENTEUParameter = cLIENTE_ID_CLIENTEU.HasValue ?
                new ObjectParameter("CLIENTE_ID_CLIENTEU", cLIENTE_ID_CLIENTEU) :
                new ObjectParameter("CLIENTE_ID_CLIENTEU", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDATE_RESERVA", iD_RESERVAUParameter, fECHA_INICIOUParameter, fECHA_FINUParameter, eSTADOUParameter, cLIENTE_ID_CLIENTEUParameter);
        }
    
        public virtual int UPDATE_SERVICIO(Nullable<decimal> iD_SERVICIOD, string nOMBREU, string tIPOU, Nullable<System.DateTime> hORARIO_INICIOU, Nullable<System.DateTime> hORARIO_FINU, string pUNTO_REUNIONU, Nullable<decimal> vALORU, string rECORRIDOU, string vEHICULOU, string cHOFERU)
        {
            var iD_SERVICIODParameter = iD_SERVICIOD.HasValue ?
                new ObjectParameter("ID_SERVICIOD", iD_SERVICIOD) :
                new ObjectParameter("ID_SERVICIOD", typeof(decimal));
    
            var nOMBREUParameter = nOMBREU != null ?
                new ObjectParameter("NOMBREU", nOMBREU) :
                new ObjectParameter("NOMBREU", typeof(string));
    
            var tIPOUParameter = tIPOU != null ?
                new ObjectParameter("TIPOU", tIPOU) :
                new ObjectParameter("TIPOU", typeof(string));
    
            var hORARIO_INICIOUParameter = hORARIO_INICIOU.HasValue ?
                new ObjectParameter("HORARIO_INICIOU", hORARIO_INICIOU) :
                new ObjectParameter("HORARIO_INICIOU", typeof(System.DateTime));
    
            var hORARIO_FINUParameter = hORARIO_FINU.HasValue ?
                new ObjectParameter("HORARIO_FINU", hORARIO_FINU) :
                new ObjectParameter("HORARIO_FINU", typeof(System.DateTime));
    
            var pUNTO_REUNIONUParameter = pUNTO_REUNIONU != null ?
                new ObjectParameter("PUNTO_REUNIONU", pUNTO_REUNIONU) :
                new ObjectParameter("PUNTO_REUNIONU", typeof(string));
    
            var vALORUParameter = vALORU.HasValue ?
                new ObjectParameter("VALORU", vALORU) :
                new ObjectParameter("VALORU", typeof(decimal));
    
            var rECORRIDOUParameter = rECORRIDOU != null ?
                new ObjectParameter("RECORRIDOU", rECORRIDOU) :
                new ObjectParameter("RECORRIDOU", typeof(string));
    
            var vEHICULOUParameter = vEHICULOU != null ?
                new ObjectParameter("VEHICULOU", vEHICULOU) :
                new ObjectParameter("VEHICULOU", typeof(string));
    
            var cHOFERUParameter = cHOFERU != null ?
                new ObjectParameter("CHOFERU", cHOFERU) :
                new ObjectParameter("CHOFERU", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDATE_SERVICIO", iD_SERVICIODParameter, nOMBREUParameter, tIPOUParameter, hORARIO_INICIOUParameter, hORARIO_FINUParameter, pUNTO_REUNIONUParameter, vALORUParameter, rECORRIDOUParameter, vEHICULOUParameter, cHOFERUParameter);
        }
    
        public virtual int UPDATE_USUARIO(string rUT_USUARIOU, string cONTRASENIAU, string rOLU, string nOMBRE_USUARIOU, string aPELLIDO_PU, string aPELLIDO_MU, string eSTADO_USUARIOU, string eMAILU)
        {
            var rUT_USUARIOUParameter = rUT_USUARIOU != null ?
                new ObjectParameter("RUT_USUARIOU", rUT_USUARIOU) :
                new ObjectParameter("RUT_USUARIOU", typeof(string));
    
            var cONTRASENIAUParameter = cONTRASENIAU != null ?
                new ObjectParameter("CONTRASENIAU", cONTRASENIAU) :
                new ObjectParameter("CONTRASENIAU", typeof(string));
    
            var rOLUParameter = rOLU != null ?
                new ObjectParameter("ROLU", rOLU) :
                new ObjectParameter("ROLU", typeof(string));
    
            var nOMBRE_USUARIOUParameter = nOMBRE_USUARIOU != null ?
                new ObjectParameter("NOMBRE_USUARIOU", nOMBRE_USUARIOU) :
                new ObjectParameter("NOMBRE_USUARIOU", typeof(string));
    
            var aPELLIDO_PUParameter = aPELLIDO_PU != null ?
                new ObjectParameter("APELLIDO_PU", aPELLIDO_PU) :
                new ObjectParameter("APELLIDO_PU", typeof(string));
    
            var aPELLIDO_MUParameter = aPELLIDO_MU != null ?
                new ObjectParameter("APELLIDO_MU", aPELLIDO_MU) :
                new ObjectParameter("APELLIDO_MU", typeof(string));
    
            var eSTADO_USUARIOUParameter = eSTADO_USUARIOU != null ?
                new ObjectParameter("ESTADO_USUARIOU", eSTADO_USUARIOU) :
                new ObjectParameter("ESTADO_USUARIOU", typeof(string));
    
            var eMAILUParameter = eMAILU != null ?
                new ObjectParameter("EMAILU", eMAILU) :
                new ObjectParameter("EMAILU", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDATE_USUARIO", rUT_USUARIOUParameter, cONTRASENIAUParameter, rOLUParameter, nOMBRE_USUARIOUParameter, aPELLIDO_PUParameter, aPELLIDO_MUParameter, eSTADO_USUARIOUParameter, eMAILUParameter);
        }
    }
}
