//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArriendoTemporada.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHECKEO
    {
        public decimal ID_CHECKEO { get; set; }
        public byte[] TIPO_CHECKEO { get; set; }
        public System.DateTime FECHA { get; set; }
        public string USUARIO_RUT_USUARIO { get; set; }
        public int RESERVA_ID_RESERVA { get; set; }
    
        public virtual RESERVA RESERVA { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
