//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArriendoTemporada.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class DPTO
    {
        public DPTO()
        {
            this.GASTOS = new HashSet<GASTOS>();
            this.INVENTARIO = new HashSet<INVENTARIO>();
            this.MANTENCION = new HashSet<MANTENCION>();
            this.REVISION_INV = new HashSet<REVISION_INV>();
            this.RESERVA = new HashSet<RESERVA>();
        }
    
        public int ID_DPTO { get; set; }
        public string NUM_DEPTO { get; set; }
        public string DIRECCION { get; set; }
        public string DESCRIPCION { get; set; }
        public string REGION { get; set; }
        public string ESTADO { get; set; }
        public int VALOR_DIARIO { get; set; }
    
        public virtual ICollection<GASTOS> GASTOS { get; set; }
        public virtual ICollection<INVENTARIO> INVENTARIO { get; set; }
        public virtual ICollection<MANTENCION> MANTENCION { get; set; }
        public virtual ICollection<REVISION_INV> REVISION_INV { get; set; }
        public virtual ICollection<RESERVA> RESERVA { get; set; }
    }
}
