//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArriendoTemporada.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESERVA
    {
        public RESERVA()
        {
            this.CHECKEO = new HashSet<CHECKEO>();
            this.MULTA = new HashSet<MULTA>();
            this.PAGO = new HashSet<PAGO>();
            this.RESERVA_SERVICIO = new HashSet<RESERVA_SERVICIO>();
            this.ACOMPANANTE = new HashSet<ACOMPANANTE>();
            this.DPTO = new HashSet<DPTO>();
        }
    
        public int ID_RESERVA { get; set; }
        public System.DateTime FECHA_INICIO { get; set; }
        public System.DateTime FECHA_FIN { get; set; }
        public short ESTADO { get; set; }
        public decimal CLIENTE_ID_CLIENTE { get; set; }
    
        public virtual ICollection<CHECKEO> CHECKEO { get; set; }
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual ICollection<MULTA> MULTA { get; set; }
        public virtual ICollection<PAGO> PAGO { get; set; }
        public virtual ICollection<RESERVA_SERVICIO> RESERVA_SERVICIO { get; set; }
        public virtual ICollection<ACOMPANANTE> ACOMPANANTE { get; set; }
        public virtual ICollection<DPTO> DPTO { get; set; }
    }
}
