//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArriendoTemporada.DALC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class ArriendoTemporadaEntities : DbContext
    {
        public ArriendoTemporadaEntities()
            : base("name=ArriendoTemporadaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ACOMPANANTE> ACOMPANANTE { get; set; }
        public DbSet<CHECKEO> CHECKEO { get; set; }
        public DbSet<CLIENTE> CLIENTE { get; set; }
        public DbSet<DPTO> DPTO { get; set; }
        public DbSet<INVENTARIO> INVENTARIO { get; set; }
        public DbSet<MANTENCION> MANTENCION { get; set; }
        public DbSet<MULTA> MULTA { get; set; }
        public DbSet<PAGO> PAGO { get; set; }
        public DbSet<RESERVA> RESERVA { get; set; }
        public DbSet<REVISION_INV> REVISION_INV { get; set; }
        public DbSet<SERVICIO> SERVICIO { get; set; }
        public DbSet<TRANSBANK> TRANSBANK { get; set; }
        public DbSet<USUARIO> USUARIO { get; set; }
        public DbSet<GASTOS> GASTOS { get; set; }
        public DbSet<RESERVA_SERVICIO> RESERVA_SERVICIO { get; set; }
    
        public virtual int DELETE_RESERVA(Nullable<decimal> iD_R)
        {
            var iD_RParameter = iD_R.HasValue ?
                new ObjectParameter("ID_R", iD_R) :
                new ObjectParameter("ID_R", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DELETE_RESERVA", iD_RParameter);
        }
    
        public virtual int INHABILITAR_CLIENTE(Nullable<decimal> iD_CLIENTE)
        {
            var iD_CLIENTEParameter = iD_CLIENTE.HasValue ?
                new ObjectParameter("ID_CLIENTE", iD_CLIENTE) :
                new ObjectParameter("ID_CLIENTE", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INHABILITAR_CLIENTE", iD_CLIENTEParameter);
        }
    
        public virtual int INHABILITAR_DPTO(Nullable<decimal> iD_DPTO)
        {
            var iD_DPTOParameter = iD_DPTO.HasValue ?
                new ObjectParameter("ID_DPTO", iD_DPTO) :
                new ObjectParameter("ID_DPTO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INHABILITAR_DPTO", iD_DPTOParameter);
        }
    
        public virtual int INHABILITAR_INVENTARIO(Nullable<decimal> iD_INV)
        {
            var iD_INVParameter = iD_INV.HasValue ?
                new ObjectParameter("ID_INV", iD_INV) :
                new ObjectParameter("ID_INV", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INHABILITAR_INVENTARIO", iD_INVParameter);
        }
    
        public virtual int INHABILITAR_SERVICIO(Nullable<decimal> iD_SERVICIO)
        {
            var iD_SERVICIOParameter = iD_SERVICIO.HasValue ?
                new ObjectParameter("ID_SERVICIO", iD_SERVICIO) :
                new ObjectParameter("ID_SERVICIO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INHABILITAR_SERVICIO", iD_SERVICIOParameter);
        }
    
        public virtual int INHABILITAR_USUARIO(string rUT_USUARIO)
        {
            var rUT_USUARIOParameter = rUT_USUARIO != null ?
                new ObjectParameter("RUT_USUARIO", rUT_USUARIO) :
                new ObjectParameter("RUT_USUARIO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INHABILITAR_USUARIO", rUT_USUARIOParameter);
        }
    
        public virtual int INSERT_CLIENTE(string rUT_CLIENTE, string pASAPORTE, string pASSWRD, string nOMBRE, string aPELLIDO_P, string aPELLIDO_M, Nullable<decimal> nUM_CELULAR, string cORREO, string nACIONALIDAD, string cLIENTE_FRECUENTE, string eSTADO_CLIENTE)
        {
            var rUT_CLIENTEParameter = rUT_CLIENTE != null ?
                new ObjectParameter("RUT_CLIENTE", rUT_CLIENTE) :
                new ObjectParameter("RUT_CLIENTE", typeof(string));
    
            var pASAPORTEParameter = pASAPORTE != null ?
                new ObjectParameter("PASAPORTE", pASAPORTE) :
                new ObjectParameter("PASAPORTE", typeof(string));
    
            var pASSWRDParameter = pASSWRD != null ?
                new ObjectParameter("PASSWRD", pASSWRD) :
                new ObjectParameter("PASSWRD", typeof(string));
    
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            var aPELLIDO_PParameter = aPELLIDO_P != null ?
                new ObjectParameter("APELLIDO_P", aPELLIDO_P) :
                new ObjectParameter("APELLIDO_P", typeof(string));
    
            var aPELLIDO_MParameter = aPELLIDO_M != null ?
                new ObjectParameter("APELLIDO_M", aPELLIDO_M) :
                new ObjectParameter("APELLIDO_M", typeof(string));
    
            var nUM_CELULARParameter = nUM_CELULAR.HasValue ?
                new ObjectParameter("NUM_CELULAR", nUM_CELULAR) :
                new ObjectParameter("NUM_CELULAR", typeof(decimal));
    
            var cORREOParameter = cORREO != null ?
                new ObjectParameter("CORREO", cORREO) :
                new ObjectParameter("CORREO", typeof(string));
    
            var nACIONALIDADParameter = nACIONALIDAD != null ?
                new ObjectParameter("NACIONALIDAD", nACIONALIDAD) :
                new ObjectParameter("NACIONALIDAD", typeof(string));
    
            var cLIENTE_FRECUENTEParameter = cLIENTE_FRECUENTE != null ?
                new ObjectParameter("CLIENTE_FRECUENTE", cLIENTE_FRECUENTE) :
                new ObjectParameter("CLIENTE_FRECUENTE", typeof(string));
    
            var eSTADO_CLIENTEParameter = eSTADO_CLIENTE != null ?
                new ObjectParameter("ESTADO_CLIENTE", eSTADO_CLIENTE) :
                new ObjectParameter("ESTADO_CLIENTE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERT_CLIENTE", rUT_CLIENTEParameter, pASAPORTEParameter, pASSWRDParameter, nOMBREParameter, aPELLIDO_PParameter, aPELLIDO_MParameter, nUM_CELULARParameter, cORREOParameter, nACIONALIDADParameter, cLIENTE_FRECUENTEParameter, eSTADO_CLIENTEParameter);
        }
    
        public virtual int INSERT_DPTO(string nUM_DEPTO, string dIRECCION, string dESCRIPCION, string rEGION, string eSTADO, Nullable<decimal> vALOR_DIARIO)
        {
            var nUM_DEPTOParameter = nUM_DEPTO != null ?
                new ObjectParameter("NUM_DEPTO", nUM_DEPTO) :
                new ObjectParameter("NUM_DEPTO", typeof(string));
    
            var dIRECCIONParameter = dIRECCION != null ?
                new ObjectParameter("DIRECCION", dIRECCION) :
                new ObjectParameter("DIRECCION", typeof(string));
    
            var dESCRIPCIONParameter = dESCRIPCION != null ?
                new ObjectParameter("DESCRIPCION", dESCRIPCION) :
                new ObjectParameter("DESCRIPCION", typeof(string));
    
            var rEGIONParameter = rEGION != null ?
                new ObjectParameter("REGION", rEGION) :
                new ObjectParameter("REGION", typeof(string));
    
            var eSTADOParameter = eSTADO != null ?
                new ObjectParameter("ESTADO", eSTADO) :
                new ObjectParameter("ESTADO", typeof(string));
    
            var vALOR_DIARIOParameter = vALOR_DIARIO.HasValue ?
                new ObjectParameter("VALOR_DIARIO", vALOR_DIARIO) :
                new ObjectParameter("VALOR_DIARIO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERT_DPTO", nUM_DEPTOParameter, dIRECCIONParameter, dESCRIPCIONParameter, rEGIONParameter, eSTADOParameter, vALOR_DIARIOParameter);
        }
    
        public virtual int INSERT_INVENTARIO(string nOMBRE_ARTI, string tIPO_ARTI, Nullable<decimal> vALOR_ARTI, Nullable<decimal> dPTO_ID_DPTO, string eSTADO_INVENTARIO)
        {
            var nOMBRE_ARTIParameter = nOMBRE_ARTI != null ?
                new ObjectParameter("NOMBRE_ARTI", nOMBRE_ARTI) :
                new ObjectParameter("NOMBRE_ARTI", typeof(string));
    
            var tIPO_ARTIParameter = tIPO_ARTI != null ?
                new ObjectParameter("TIPO_ARTI", tIPO_ARTI) :
                new ObjectParameter("TIPO_ARTI", typeof(string));
    
            var vALOR_ARTIParameter = vALOR_ARTI.HasValue ?
                new ObjectParameter("VALOR_ARTI", vALOR_ARTI) :
                new ObjectParameter("VALOR_ARTI", typeof(decimal));
    
            var dPTO_ID_DPTOParameter = dPTO_ID_DPTO.HasValue ?
                new ObjectParameter("DPTO_ID_DPTO", dPTO_ID_DPTO) :
                new ObjectParameter("DPTO_ID_DPTO", typeof(decimal));
    
            var eSTADO_INVENTARIOParameter = eSTADO_INVENTARIO != null ?
                new ObjectParameter("ESTADO_INVENTARIO", eSTADO_INVENTARIO) :
                new ObjectParameter("ESTADO_INVENTARIO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERT_INVENTARIO", nOMBRE_ARTIParameter, tIPO_ARTIParameter, vALOR_ARTIParameter, dPTO_ID_DPTOParameter, eSTADO_INVENTARIOParameter);
        }
    
        public virtual int INSERT_RESERVA(Nullable<System.DateTime> fECHA_INICIO, Nullable<System.DateTime> fECHA_FIN, string eSTADO, Nullable<decimal> cLIENTE_ID_CLIENTE)
        {
            var fECHA_INICIOParameter = fECHA_INICIO.HasValue ?
                new ObjectParameter("FECHA_INICIO", fECHA_INICIO) :
                new ObjectParameter("FECHA_INICIO", typeof(System.DateTime));
    
            var fECHA_FINParameter = fECHA_FIN.HasValue ?
                new ObjectParameter("FECHA_FIN", fECHA_FIN) :
                new ObjectParameter("FECHA_FIN", typeof(System.DateTime));
    
            var eSTADOParameter = eSTADO != null ?
                new ObjectParameter("ESTADO", eSTADO) :
                new ObjectParameter("ESTADO", typeof(string));
    
            var cLIENTE_ID_CLIENTEParameter = cLIENTE_ID_CLIENTE.HasValue ?
                new ObjectParameter("CLIENTE_ID_CLIENTE", cLIENTE_ID_CLIENTE) :
                new ObjectParameter("CLIENTE_ID_CLIENTE", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERT_RESERVA", fECHA_INICIOParameter, fECHA_FINParameter, eSTADOParameter, cLIENTE_ID_CLIENTEParameter);
        }
    
        public virtual int INSERT_SERVICIO(string nOMBRE, string tIPO, Nullable<System.DateTime> hORARIO_INICIO, Nullable<System.DateTime> hORARIO_FIN, string pUNTO_REUNION, Nullable<decimal> vALOR, string rECORRIDO, string vEHICULO, string cHOFER, string eSTADO_SERVICIO, Nullable<decimal> cUPO)
        {
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            var tIPOParameter = tIPO != null ?
                new ObjectParameter("TIPO", tIPO) :
                new ObjectParameter("TIPO", typeof(string));
    
            var hORARIO_INICIOParameter = hORARIO_INICIO.HasValue ?
                new ObjectParameter("HORARIO_INICIO", hORARIO_INICIO) :
                new ObjectParameter("HORARIO_INICIO", typeof(System.DateTime));
    
            var hORARIO_FINParameter = hORARIO_FIN.HasValue ?
                new ObjectParameter("HORARIO_FIN", hORARIO_FIN) :
                new ObjectParameter("HORARIO_FIN", typeof(System.DateTime));
    
            var pUNTO_REUNIONParameter = pUNTO_REUNION != null ?
                new ObjectParameter("PUNTO_REUNION", pUNTO_REUNION) :
                new ObjectParameter("PUNTO_REUNION", typeof(string));
    
            var vALORParameter = vALOR.HasValue ?
                new ObjectParameter("VALOR", vALOR) :
                new ObjectParameter("VALOR", typeof(decimal));
    
            var rECORRIDOParameter = rECORRIDO != null ?
                new ObjectParameter("RECORRIDO", rECORRIDO) :
                new ObjectParameter("RECORRIDO", typeof(string));
    
            var vEHICULOParameter = vEHICULO != null ?
                new ObjectParameter("VEHICULO", vEHICULO) :
                new ObjectParameter("VEHICULO", typeof(string));
    
            var cHOFERParameter = cHOFER != null ?
                new ObjectParameter("CHOFER", cHOFER) :
                new ObjectParameter("CHOFER", typeof(string));
    
            var eSTADO_SERVICIOParameter = eSTADO_SERVICIO != null ?
                new ObjectParameter("ESTADO_SERVICIO", eSTADO_SERVICIO) :
                new ObjectParameter("ESTADO_SERVICIO", typeof(string));
    
            var cUPOParameter = cUPO.HasValue ?
                new ObjectParameter("CUPO", cUPO) :
                new ObjectParameter("CUPO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERT_SERVICIO", nOMBREParameter, tIPOParameter, hORARIO_INICIOParameter, hORARIO_FINParameter, pUNTO_REUNIONParameter, vALORParameter, rECORRIDOParameter, vEHICULOParameter, cHOFERParameter, eSTADO_SERVICIOParameter, cUPOParameter);
        }
    
        public virtual int INSERT_USUARIO(string rUT_USUARIO, string cONTRASENIA, string rOL, string nOMBRE_USUARIO, string aPELLIDO_P, string aPELLIDO_M, string eSTADO_USUARIO, string eMAIL)
        {
            var rUT_USUARIOParameter = rUT_USUARIO != null ?
                new ObjectParameter("RUT_USUARIO", rUT_USUARIO) :
                new ObjectParameter("RUT_USUARIO", typeof(string));
    
            var cONTRASENIAParameter = cONTRASENIA != null ?
                new ObjectParameter("CONTRASENIA", cONTRASENIA) :
                new ObjectParameter("CONTRASENIA", typeof(string));
    
            var rOLParameter = rOL != null ?
                new ObjectParameter("ROL", rOL) :
                new ObjectParameter("ROL", typeof(string));
    
            var nOMBRE_USUARIOParameter = nOMBRE_USUARIO != null ?
                new ObjectParameter("NOMBRE_USUARIO", nOMBRE_USUARIO) :
                new ObjectParameter("NOMBRE_USUARIO", typeof(string));
    
            var aPELLIDO_PParameter = aPELLIDO_P != null ?
                new ObjectParameter("APELLIDO_P", aPELLIDO_P) :
                new ObjectParameter("APELLIDO_P", typeof(string));
    
            var aPELLIDO_MParameter = aPELLIDO_M != null ?
                new ObjectParameter("APELLIDO_M", aPELLIDO_M) :
                new ObjectParameter("APELLIDO_M", typeof(string));
    
            var eSTADO_USUARIOParameter = eSTADO_USUARIO != null ?
                new ObjectParameter("ESTADO_USUARIO", eSTADO_USUARIO) :
                new ObjectParameter("ESTADO_USUARIO", typeof(string));
    
            var eMAILParameter = eMAIL != null ?
                new ObjectParameter("EMAIL", eMAIL) :
                new ObjectParameter("EMAIL", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERT_USUARIO", rUT_USUARIOParameter, cONTRASENIAParameter, rOLParameter, nOMBRE_USUARIOParameter, aPELLIDO_PParameter, aPELLIDO_MParameter, eSTADO_USUARIOParameter, eMAILParameter);
        }
    
        public virtual int UPDATE_CLIENTE(Nullable<decimal> iD_CLIENTEC, string rUT_CLIENTEC, string pASAPORTEC, string nOMBREC, string aPELLIDO_PC, string aPELLIDO_MC, Nullable<decimal> nUM_CELULARC, string cORREOC, string nACIONALIDADC, string cLIENTE_FRECUENTEC, string eSTADO_CLIENTEC)
        {
            var iD_CLIENTECParameter = iD_CLIENTEC.HasValue ?
                new ObjectParameter("ID_CLIENTEC", iD_CLIENTEC) :
                new ObjectParameter("ID_CLIENTEC", typeof(decimal));
    
            var rUT_CLIENTECParameter = rUT_CLIENTEC != null ?
                new ObjectParameter("RUT_CLIENTEC", rUT_CLIENTEC) :
                new ObjectParameter("RUT_CLIENTEC", typeof(string));
    
            var pASAPORTECParameter = pASAPORTEC != null ?
                new ObjectParameter("PASAPORTEC", pASAPORTEC) :
                new ObjectParameter("PASAPORTEC", typeof(string));
    
            var nOMBRECParameter = nOMBREC != null ?
                new ObjectParameter("NOMBREC", nOMBREC) :
                new ObjectParameter("NOMBREC", typeof(string));
    
            var aPELLIDO_PCParameter = aPELLIDO_PC != null ?
                new ObjectParameter("APELLIDO_PC", aPELLIDO_PC) :
                new ObjectParameter("APELLIDO_PC", typeof(string));
    
            var aPELLIDO_MCParameter = aPELLIDO_MC != null ?
                new ObjectParameter("APELLIDO_MC", aPELLIDO_MC) :
                new ObjectParameter("APELLIDO_MC", typeof(string));
    
            var nUM_CELULARCParameter = nUM_CELULARC.HasValue ?
                new ObjectParameter("NUM_CELULARC", nUM_CELULARC) :
                new ObjectParameter("NUM_CELULARC", typeof(decimal));
    
            var cORREOCParameter = cORREOC != null ?
                new ObjectParameter("CORREOC", cORREOC) :
                new ObjectParameter("CORREOC", typeof(string));
    
            var nACIONALIDADCParameter = nACIONALIDADC != null ?
                new ObjectParameter("NACIONALIDADC", nACIONALIDADC) :
                new ObjectParameter("NACIONALIDADC", typeof(string));
    
            var cLIENTE_FRECUENTECParameter = cLIENTE_FRECUENTEC != null ?
                new ObjectParameter("CLIENTE_FRECUENTEC", cLIENTE_FRECUENTEC) :
                new ObjectParameter("CLIENTE_FRECUENTEC", typeof(string));
    
            var eSTADO_CLIENTECParameter = eSTADO_CLIENTEC != null ?
                new ObjectParameter("ESTADO_CLIENTEC", eSTADO_CLIENTEC) :
                new ObjectParameter("ESTADO_CLIENTEC", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDATE_CLIENTE", iD_CLIENTECParameter, rUT_CLIENTECParameter, pASAPORTECParameter, nOMBRECParameter, aPELLIDO_PCParameter, aPELLIDO_MCParameter, nUM_CELULARCParameter, cORREOCParameter, nACIONALIDADCParameter, cLIENTE_FRECUENTECParameter, eSTADO_CLIENTECParameter);
        }
    
        public virtual int UPDATE_DPTO(Nullable<decimal> iD_DPTOD, string nUM_DEPTOD, string dIRECCIOND, string dESCRIPCIOND, string rEGIOND, string eSTADOD, Nullable<decimal> vALOR_DIARIOD)
        {
            var iD_DPTODParameter = iD_DPTOD.HasValue ?
                new ObjectParameter("ID_DPTOD", iD_DPTOD) :
                new ObjectParameter("ID_DPTOD", typeof(decimal));
    
            var nUM_DEPTODParameter = nUM_DEPTOD != null ?
                new ObjectParameter("NUM_DEPTOD", nUM_DEPTOD) :
                new ObjectParameter("NUM_DEPTOD", typeof(string));
    
            var dIRECCIONDParameter = dIRECCIOND != null ?
                new ObjectParameter("DIRECCIOND", dIRECCIOND) :
                new ObjectParameter("DIRECCIOND", typeof(string));
    
            var dESCRIPCIONDParameter = dESCRIPCIOND != null ?
                new ObjectParameter("DESCRIPCIOND", dESCRIPCIOND) :
                new ObjectParameter("DESCRIPCIOND", typeof(string));
    
            var rEGIONDParameter = rEGIOND != null ?
                new ObjectParameter("REGIOND", rEGIOND) :
                new ObjectParameter("REGIOND", typeof(string));
    
            var eSTADODParameter = eSTADOD != null ?
                new ObjectParameter("ESTADOD", eSTADOD) :
                new ObjectParameter("ESTADOD", typeof(string));
    
            var vALOR_DIARIODParameter = vALOR_DIARIOD.HasValue ?
                new ObjectParameter("VALOR_DIARIOD", vALOR_DIARIOD) :
                new ObjectParameter("VALOR_DIARIOD", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDATE_DPTO", iD_DPTODParameter, nUM_DEPTODParameter, dIRECCIONDParameter, dESCRIPCIONDParameter, rEGIONDParameter, eSTADODParameter, vALOR_DIARIODParameter);
        }
    
        public virtual int UPDATE_INVENTARIO(Nullable<decimal> iD_INVI, string nOMBRE_ARTII, string tIPO_ARTII, Nullable<decimal> vALOR_ARTII, Nullable<decimal> dPTO_ID_DPTOI, string eSTADO_INVENTARIOI)
        {
            var iD_INVIParameter = iD_INVI.HasValue ?
                new ObjectParameter("ID_INVI", iD_INVI) :
                new ObjectParameter("ID_INVI", typeof(decimal));
    
            var nOMBRE_ARTIIParameter = nOMBRE_ARTII != null ?
                new ObjectParameter("NOMBRE_ARTII", nOMBRE_ARTII) :
                new ObjectParameter("NOMBRE_ARTII", typeof(string));
    
            var tIPO_ARTIIParameter = tIPO_ARTII != null ?
                new ObjectParameter("TIPO_ARTII", tIPO_ARTII) :
                new ObjectParameter("TIPO_ARTII", typeof(string));
    
            var vALOR_ARTIIParameter = vALOR_ARTII.HasValue ?
                new ObjectParameter("VALOR_ARTII", vALOR_ARTII) :
                new ObjectParameter("VALOR_ARTII", typeof(decimal));
    
            var dPTO_ID_DPTOIParameter = dPTO_ID_DPTOI.HasValue ?
                new ObjectParameter("DPTO_ID_DPTOI", dPTO_ID_DPTOI) :
                new ObjectParameter("DPTO_ID_DPTOI", typeof(decimal));
    
            var eSTADO_INVENTARIOIParameter = eSTADO_INVENTARIOI != null ?
                new ObjectParameter("ESTADO_INVENTARIOI", eSTADO_INVENTARIOI) :
                new ObjectParameter("ESTADO_INVENTARIOI", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDATE_INVENTARIO", iD_INVIParameter, nOMBRE_ARTIIParameter, tIPO_ARTIIParameter, vALOR_ARTIIParameter, dPTO_ID_DPTOIParameter, eSTADO_INVENTARIOIParameter);
        }
    
        public virtual int UPDATE_RESERVA(Nullable<decimal> iD_RESERVAU, Nullable<System.DateTime> fECHA_INICIOU, Nullable<System.DateTime> fECHA_FINU, string eSTADOU, Nullable<decimal> cLIENTE_ID_CLIENTEU)
        {
            var iD_RESERVAUParameter = iD_RESERVAU.HasValue ?
                new ObjectParameter("ID_RESERVAU", iD_RESERVAU) :
                new ObjectParameter("ID_RESERVAU", typeof(decimal));
    
            var fECHA_INICIOUParameter = fECHA_INICIOU.HasValue ?
                new ObjectParameter("FECHA_INICIOU", fECHA_INICIOU) :
                new ObjectParameter("FECHA_INICIOU", typeof(System.DateTime));
    
            var fECHA_FINUParameter = fECHA_FINU.HasValue ?
                new ObjectParameter("FECHA_FINU", fECHA_FINU) :
                new ObjectParameter("FECHA_FINU", typeof(System.DateTime));
    
            var eSTADOUParameter = eSTADOU != null ?
                new ObjectParameter("ESTADOU", eSTADOU) :
                new ObjectParameter("ESTADOU", typeof(string));
    
            var cLIENTE_ID_CLIENTEUParameter = cLIENTE_ID_CLIENTEU.HasValue ?
                new ObjectParameter("CLIENTE_ID_CLIENTEU", cLIENTE_ID_CLIENTEU) :
                new ObjectParameter("CLIENTE_ID_CLIENTEU", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDATE_RESERVA", iD_RESERVAUParameter, fECHA_INICIOUParameter, fECHA_FINUParameter, eSTADOUParameter, cLIENTE_ID_CLIENTEUParameter);
        }
    
        public virtual int UPDATE_SERVICIO(Nullable<decimal> iD_SERVICIOS, string nOMBRES, string tIPOS, Nullable<System.DateTime> hORARIO_INICIOS, Nullable<System.DateTime> hORARIO_FINS, string pUNTO_REUNIONS, Nullable<decimal> vALORS, string rECORRIDOS, string vEHICULOS, string cHOFERS, string eSTADO_SERVICIOS, Nullable<decimal> cUPOS)
        {
            var iD_SERVICIOSParameter = iD_SERVICIOS.HasValue ?
                new ObjectParameter("ID_SERVICIOS", iD_SERVICIOS) :
                new ObjectParameter("ID_SERVICIOS", typeof(decimal));
    
            var nOMBRESParameter = nOMBRES != null ?
                new ObjectParameter("NOMBRES", nOMBRES) :
                new ObjectParameter("NOMBRES", typeof(string));
    
            var tIPOSParameter = tIPOS != null ?
                new ObjectParameter("TIPOS", tIPOS) :
                new ObjectParameter("TIPOS", typeof(string));
    
            var hORARIO_INICIOSParameter = hORARIO_INICIOS.HasValue ?
                new ObjectParameter("HORARIO_INICIOS", hORARIO_INICIOS) :
                new ObjectParameter("HORARIO_INICIOS", typeof(System.DateTime));
    
            var hORARIO_FINSParameter = hORARIO_FINS.HasValue ?
                new ObjectParameter("HORARIO_FINS", hORARIO_FINS) :
                new ObjectParameter("HORARIO_FINS", typeof(System.DateTime));
    
            var pUNTO_REUNIONSParameter = pUNTO_REUNIONS != null ?
                new ObjectParameter("PUNTO_REUNIONS", pUNTO_REUNIONS) :
                new ObjectParameter("PUNTO_REUNIONS", typeof(string));
    
            var vALORSParameter = vALORS.HasValue ?
                new ObjectParameter("VALORS", vALORS) :
                new ObjectParameter("VALORS", typeof(decimal));
    
            var rECORRIDOSParameter = rECORRIDOS != null ?
                new ObjectParameter("RECORRIDOS", rECORRIDOS) :
                new ObjectParameter("RECORRIDOS", typeof(string));
    
            var vEHICULOSParameter = vEHICULOS != null ?
                new ObjectParameter("VEHICULOS", vEHICULOS) :
                new ObjectParameter("VEHICULOS", typeof(string));
    
            var cHOFERSParameter = cHOFERS != null ?
                new ObjectParameter("CHOFERS", cHOFERS) :
                new ObjectParameter("CHOFERS", typeof(string));
    
            var eSTADO_SERVICIOSParameter = eSTADO_SERVICIOS != null ?
                new ObjectParameter("ESTADO_SERVICIOS", eSTADO_SERVICIOS) :
                new ObjectParameter("ESTADO_SERVICIOS", typeof(string));
    
            var cUPOSParameter = cUPOS.HasValue ?
                new ObjectParameter("CUPOS", cUPOS) :
                new ObjectParameter("CUPOS", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDATE_SERVICIO", iD_SERVICIOSParameter, nOMBRESParameter, tIPOSParameter, hORARIO_INICIOSParameter, hORARIO_FINSParameter, pUNTO_REUNIONSParameter, vALORSParameter, rECORRIDOSParameter, vEHICULOSParameter, cHOFERSParameter, eSTADO_SERVICIOSParameter, cUPOSParameter);
        }
    
        public virtual int UPDATE_USUARIO(string rUT_USUARIOU, string rOLU, string nOMBRE_USUARIOU, string aPELLIDO_PU, string aPELLIDO_MU, string eSTADO_USUARIOU, string eMAILU)
        {
            var rUT_USUARIOUParameter = rUT_USUARIOU != null ?
                new ObjectParameter("RUT_USUARIOU", rUT_USUARIOU) :
                new ObjectParameter("RUT_USUARIOU", typeof(string));
    
            var rOLUParameter = rOLU != null ?
                new ObjectParameter("ROLU", rOLU) :
                new ObjectParameter("ROLU", typeof(string));
    
            var nOMBRE_USUARIOUParameter = nOMBRE_USUARIOU != null ?
                new ObjectParameter("NOMBRE_USUARIOU", nOMBRE_USUARIOU) :
                new ObjectParameter("NOMBRE_USUARIOU", typeof(string));
    
            var aPELLIDO_PUParameter = aPELLIDO_PU != null ?
                new ObjectParameter("APELLIDO_PU", aPELLIDO_PU) :
                new ObjectParameter("APELLIDO_PU", typeof(string));
    
            var aPELLIDO_MUParameter = aPELLIDO_MU != null ?
                new ObjectParameter("APELLIDO_MU", aPELLIDO_MU) :
                new ObjectParameter("APELLIDO_MU", typeof(string));
    
            var eSTADO_USUARIOUParameter = eSTADO_USUARIOU != null ?
                new ObjectParameter("ESTADO_USUARIOU", eSTADO_USUARIOU) :
                new ObjectParameter("ESTADO_USUARIOU", typeof(string));
    
            var eMAILUParameter = eMAILU != null ?
                new ObjectParameter("EMAILU", eMAILU) :
                new ObjectParameter("EMAILU", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDATE_USUARIO", rUT_USUARIOUParameter, rOLUParameter, nOMBRE_USUARIOUParameter, aPELLIDO_PUParameter, aPELLIDO_MUParameter, eSTADO_USUARIOUParameter, eMAILUParameter);
        }
    
        public virtual int INSERT_RESERVA_SERVICIO(Nullable<decimal> rESERVA_ID_RESERVA, Nullable<decimal> sERVICIO_ID_SERVICIO, Nullable<decimal> cANTIDAD_CUPO)
        {
            var rESERVA_ID_RESERVAParameter = rESERVA_ID_RESERVA.HasValue ?
                new ObjectParameter("RESERVA_ID_RESERVA", rESERVA_ID_RESERVA) :
                new ObjectParameter("RESERVA_ID_RESERVA", typeof(decimal));
    
            var sERVICIO_ID_SERVICIOParameter = sERVICIO_ID_SERVICIO.HasValue ?
                new ObjectParameter("SERVICIO_ID_SERVICIO", sERVICIO_ID_SERVICIO) :
                new ObjectParameter("SERVICIO_ID_SERVICIO", typeof(decimal));
    
            var cANTIDAD_CUPOParameter = cANTIDAD_CUPO.HasValue ?
                new ObjectParameter("CANTIDAD_CUPO", cANTIDAD_CUPO) :
                new ObjectParameter("CANTIDAD_CUPO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERT_RESERVA_SERVICIO", rESERVA_ID_RESERVAParameter, sERVICIO_ID_SERVICIOParameter, cANTIDAD_CUPOParameter);
        }
    }
}
