//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArriendoTemporada.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVENTARIO
    {
        public int ID_INV { get; set; }
        public string NOMBRE_ARTI { get; set; }
        public string TIPO_ARTI { get; set; }
        public int VALOR_ARTI { get; set; }
        public int DPTO_ID_DPTO { get; set; }
        public string ESTADO_INVENTARIO { get; set; }
    
        public virtual DPTO DPTO { get; set; }
    }
}
