//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArriendoTemporada.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class MANTENCION
    {
        public int ID_MANTECION { get; set; }
        public string DESCRIPCION { get; set; }
        public decimal VALOR { get; set; }
        public System.DateTime FECHA_INI { get; set; }
        public System.DateTime FECHA_TERM { get; set; }
        public int DPTO_ID_DPTO { get; set; }
    
        public virtual DPTO DPTO { get; set; }
    }
}
