//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArriendoTemporada.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICIO
    {
        public SERVICIO()
        {
            this.RESERVA_SERVICIO = new HashSet<RESERVA_SERVICIO>();
        }
    
        public int ID_SERVICIO { get; set; }
        public string NOMBRE { get; set; }
        public string TIPO { get; set; }
        public System.DateTime HORARIO_INICIO { get; set; }
        public System.DateTime HORARIO_FIN { get; set; }
        public string PUNTO_REUNION { get; set; }
        public int VALOR { get; set; }
        public string RECORRIDO { get; set; }
        public string VEHICULO { get; set; }
        public string CHOFER { get; set; }
        public string ESTADO_SERVICIO { get; set; }
        public int CUPO { get; set; }
    
        public virtual ICollection<RESERVA_SERVICIO> RESERVA_SERVICIO { get; set; }
    }
}
