//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArriendoTemporada.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSBANK
    {
        public TRANSBANK()
        {
            this.PAGO = new HashSet<PAGO>();
        }
    
        public decimal ID_TRANSBANK { get; set; }
        public decimal TOTAL_TBK { get; set; }
        public string ESTADO_TBK { get; set; }
        public System.DateTime FECHA_TBK { get; set; }
    
        public virtual ICollection<PAGO> PAGO { get; set; }
    }
}
