//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArriendoTemporada.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public USUARIO()
        {
            this.CHECKEO = new HashSet<CHECKEO>();
            this.REVISION_INV = new HashSet<REVISION_INV>();
        }
    
        public string RUT_USUARIO { get; set; }
        public string CONTRASENIA { get; set; }
        public string ROL { get; set; }
        public string NOMBRE_USUARIO { get; set; }
        public string APELLIDO_P { get; set; }
        public string APELLIDO_M { get; set; }
        public string ESTADO_USUARIO { get; set; }
        public string EMAIL { get; set; }
    
        public virtual ICollection<CHECKEO> CHECKEO { get; set; }
        public virtual ICollection<REVISION_INV> REVISION_INV { get; set; }
    }
}
